# ============ BASIC ============
run:
    tissue: Brain
    additional_tissues: []
    seed_include_terms: [epilep, seizure]
    exclude_terms: []
    additional_include_terms: [nerve, nervous, neuronal, cerebellum, cerebral, hippocampus, hypothalamus]
    phenotype: Epilepsy # user-defined descriptive term for disease/phenotype
    run_id: production # output folder name suffix
pu_params:
    classifiers: [ExtraTreesClassifier, RandomForestClassifier] #, XGBoost, DNN, SVC, GradientBoostingClassifier, Stacking]
    iterations: 10 # default: 10
    nthreads: 4 # default: 4 (or as many CPUs available)
run_steps:
    run_boruta: False # default: False
    run_unsupervised: True # default: True


# ============ ADVANCED ============
run_advanced:
    gene_annot_list: [ATP1A3, KCNA2, KCNQ2, AFG3L2, SCN1A, EEF1A2, MTOR, AMT, FGFR1, FAT4, ARNT2] # [optional] for highlighting in plots
    anchor_genes: [ATP1A3, KCNA2, KCNQ2, AFG3L2, SCN1A, EEF1A2, MTOR, AMT, FGFR1, FAT4, ARNT2] # [optional/beta] for highlighting in plots
    include_disease_features: True
    generic_classifier: None # None (default), All (default for Generic), AD, AR, AD_only, AR_only
    hide_seed_genes_ratio: 0 # default: 0 (keep all seed genes)
    seed_pos_ratio: 0.8 #default: 0.8
    random_seeds: False
supervised_filters:
    feature_selection: None # Options: boruta, None
    boruta_iterations: 1 # default: 100
    boruta_decision_thres: 90 # default: 90
    add_original_features_in_stacking: True # default: True
    test_size: 0.2 # default: 0.2
    balancing_ratio: 1.5 # default: 1.5
    random_fold_split: True # use False for parameter GridSearch and debugging
    kfold: 10 # default: 10
static:
    Y_label: known_gene
    gene_name: Gene_Name
    data_dir: ./data
eda_filters:
    drop_missing_data_features: True
    discard_highly_correlated: True
    drop_gene_len_features: False
    manual_feature_selection: False
    create_plots: True
eda_parameters:
    high_corr_thres: 0.8 # default: 0.8
    missing_data_thres: 0.25 # default: 0.25
